#!/usr/bin/env bash
# Generates .work/BOARD.md from .work/*.md task files -- never hand-edit
cd "$(dirname "$0")" || exit 1
field() { grep -m1 "^$2:" "$1" 2>/dev/null | sed 's/^[^:]*: *//; s/ *#.*//'; }
gate=$(cat GATE 2>/dev/null || echo UNKNOWN)
{
  echo "# BOARD.md -- generated by board.sh, never hand-edit"
  echo "Gate (npx vitest run): $gate"
  echo "| Task | Status | Owner | Claimed | Completed |"
  echo "|---|---|---|---|---|"
  done=0
  for f in T-*.md; do
    [ -e "$f" ] || continue
    echo "| $(field "$f" id) | $(field "$f" status) | $(field "$f" owner) | $(field "$f" claimed) | $(field "$f" completed) |"
    [ "$(field "$f" status)" = DONE ] && done=$((done+1))
  done
  echo "Absent task file means TODO. DONE: $done / 69"
} > BOARD.md
